#!/bin/bash

# Set the Hugo Version
VERSION='0.72.0'

# Build the Image
docker build --build-arg VERSION=$VERSION -f $DOCKERFILE_PATH -t $DOCKER_REPO:$VERSION .

# Build the Image
docker push $DOCKER_REPO:$VERSION
